### ISSUE TITLE
Crashed in 1.13.2

### ISSUE THREAD

**Issue by ghost** [Elemend/Vein-Miner-Unified#1]
I created new world and installed the Vein-Miner-Unified datapack with no configulation in minecraft 1.13.2.
After the install, I loaded the world then crashed and got following log:
```
[00:44:40] [Client thread/INFO]: Setting user: ***
[00:44:42] [Client thread/WARN]: Skipping bad option: lastServer:
[00:44:42] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
[00:44:43] [Client thread/INFO]: Reloading ResourceManager: Default
[00:44:44] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:44:44] [Thread-2/INFO]: Initializing No Sound
[00:44:44] [Thread-2/INFO]: (Silent Mode)
[00:44:44] [Thread-2/INFO]: OpenAL initialized.
[00:44:45] [Sound Library Loader/INFO]: Preloading sound minecraft:sounds/ambient/underwater/underwater_ambience.ogg
[00:44:45] [Sound Library Loader/INFO]: Sound engine started
[00:44:49] [Client thread/INFO]: Created: 1024x512 textures-atlas
[00:44:50] [Client thread/INFO]: Narrator library for x64 successfully loaded
[00:46:11] [Client thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:46:11] [Client thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:46:11] [Client thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:46:11] [Client thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:46:11] [Client thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:46:11] [Client thread/INFO]: Loaded 0 recipes
[00:46:11] [Client thread/INFO]: Loaded 0 advancements
[00:46:11] [Server thread/INFO]: Starting integrated minecraft server version 1.13.2
[00:46:11] [Server thread/INFO]: Generating keypair
[00:46:11] [Server thread/INFO]: Found new data pack file/vein_miner_unified.zip, loading it automatically
[00:46:11] [Server thread/INFO]: Reloading ResourceManager: Default, vein_miner_unified.zip
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag1 from vm:tags/blocks/tag1.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:wither_rose'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag2 from vm:tags/blocks/tag2.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:diorite_slab'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag3 from vm:tags/blocks/tag3.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:diorite_slab'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag4 from vm:tags/blocks/tag4.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:wither_rose'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag5 from vm:tags/blocks/tag5.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:brick_wall'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag6 from vm:tags/blocks/tag6.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:polished_granite_slab'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag7 from vm:tags/blocks/tag7.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:lily_of_the_valley'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag8 from vm:tags/blocks/tag8.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:lily_of_the_valley'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't read block tag list vm:tag9 from vm:tags/blocks/tag9.json in data pack vein_miner_unified.zip
com.google.gson.JsonParseException: Unknown value 'minecraft:wither_rose'
	at wz$a.a(SourceFile:149) ~[1.13.2.jar:?]
	at xa.a(SourceFile:102) [1.13.2.jar:?]
	at xb.a(SourceFile:37) [1.13.2.jar:?]
	at vh.c(SourceFile:124) [1.13.2.jar:?]
	at vh.a(SourceFile:107) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) [1.13.2.jar:?]
	at dgh.a(SourceFile:83) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: Couldn't load block tag vm:axeblocks as it either references another tag that doesn't exist, or ultimately references itself
[00:46:11] [Server thread/ERROR]: Couldn't load block tag vm:alltools as it either references another tag that doesn't exist, or ultimately references itself
[00:46:11] [Server thread/ERROR]: Couldn't load block tag vm:shovelblocks as it either references another tag that doesn't exist, or ultimately references itself
[00:46:11] [Server thread/ERROR]: Couldn't load block tag vm:pickblocks as it either references another tag that doesn't exist, or ultimately references itself
[00:46:11] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Cannot build unresolved tag entry
	at wz$c.a(SourceFile:225) ~[1.13.2.jar:?]
	at wz.<init>(SourceFile:38) ~[1.13.2.jar:?]
	at wz$a.b(SourceFile:131) ~[1.13.2.jar:?]
	at xa.a(SourceFile:135) ~[1.13.2.jar:?]
	at xb.a(SourceFile:37) ~[1.13.2.jar:?]
	at vh.c(SourceFile:124) ~[1.13.2.jar:?]
	at vh.a(SourceFile:107) ~[1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:1399) ~[1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:400) ~[1.13.2.jar:?]
	at dgh.a(SourceFile:83) ~[1.13.2.jar:?]
	at dgh.d(SourceFile:108) ~[1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:46:11] [Server thread/ERROR]: This crash report has been saved to: C:\Users\***\AppData\Roaming\.minecraft\crash-reports\crash-2019-01-13_00.46.11-server.txt
[00:46:11] [Server thread/INFO]: Stopping server
[00:46:11] [Server thread/INFO]: Saving players
[00:46:11] [Server thread/INFO]: Saving worlds
[00:46:11] [Client Shutdown Thread/INFO]: Stopping server
[00:46:11] [Client Shutdown Thread/INFO]: Saving players
[00:46:11] [Client Shutdown Thread/INFO]: Saving worlds
```

**Comment by Elemend** [comment]
That's no surprise as it only works in 1.14-Snapshots. The report says it: In 1.13.2 there is no wither_rose, brick_wall and so on.
 I updated the readme so it's more clear. I'll have a Version for 1.13 ready eventually.

**Comment by ghost** [comment]
Thanks. I'll be waiting for 1.13 ready version.

**Comment by Elemend** [comment]
It's done finally. Added A Version for 1.13.2. If there are any typos in the functions that may break things, let me know. There may still be some left that I missed.
